version: '3.7'
services:

  db:
    image: mysql:8.0.23
    ports:
      - 4306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    command: --default-authentication-plugin=mysql_native_password
  test_db:
    image: mysql:8.0.23
    ports:
      - 4307:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    command: --default-authentication-plugin=mysql_native_password
  app: &app
    build:
      context: .
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - .:/my_app:cached
    command: >
      /bin/bash -c "
        rm -rf tmp/pids/server.pid &&
        bundle exec rails db:migrate &&
        bundle exec rails s -p 3000 -b '0.0.0.0'
        ./bin/webpack-dev-server
      "
    ports:
      - "80:3000"
    depends_on:
      - db
      - test_db
      - chrome
    environment:
      TZ: Japan
      RAILS_ENV: development
      MYSQL_HOST: db
      MYSQL_DB_NAME: app
      MYSQL_TEST_DB_NAME: test_app
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      WEBPACKER_DEV_SERVER_HOST: webpacker
      SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub
  webpacker:
    <<: *app
    command: ./bin/webpack-dev-server
    environment:
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    ports:
      - "3035:3035"
  chrome:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
volumes:
  mysql-data:
    driver: local
